name: Deploy Frontend (React)

on:
  push:
    branches:
      - 'feat/**'
      - dev
  pull_request:
    branches: [dev]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Workspace Dependencies
        run: yarn install

      - name: Build React App
        working-directory: ./packages/frontend
        run: yarn build
        env:
          REACT_APP_API_URL: https://api.serhiigrin4-games.pp.ua/
          VITE_API_URL: https://api.serhiigrin4-games.pp.ua/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        working-directory: ./packages/frontend/dist
        run: aws s3 sync . s3://serhiigrin4-notes-frontend-app --delete